services:
  ppstructurev3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - ./cache:/root/.cache
    command: >
      uvicorn app.server:app --host 0.0.0.0 --port 8000 --workers 2
