services:
  ppstructurev3:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "${PORT}"
    volumes:
      - paddle_cache:/root/.paddlex
      - paddle_models:/root/.paddleocr

volumes:
  paddle_cache:
  paddle_models:
