services:
  ppstructurev3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PY_VERSION: "${PY_VERSION}"
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    command: >
      uvicorn app.server:app --host ${HOST} --port ${PORT} --workers ${WORKERS}
    restart: unless-stopped
