services:
  paddleocr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paddleocr
    restart: always
    command: ["hub", "serving", "start", "-m", "ocr_system", "-p", "8868"]
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ai-automation-shared

networks:
  ai-automation-shared:
    external: true
    name: ai-automation-shared
