services:
  ppstructurev3:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "${PORT:-8080}"
    volumes:
      - paddle_cache:/root/.paddlex
      - paddle_models:/root/.paddleocr
    restart: unless-stopped

volumes:
  paddle_cache:
  paddle_models:
