services:
  ppstructurev3:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./cache:/root/.cache
    command: >
      uvicorn app.server:app --host 0.0.0.0 --port 8000 --workers 1
