services:
  ppstructure:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    env_file:
      - .env
    volumes:
      - models-cache:/root/.paddlex
      - tmp-cache:/tmp

volumes:
  models-cache:
  tmp-cache:
