services:
  ppstructurev3:
    build:
      context: .
      dockerfile: Dockerfile
    image: ppstructurev3-arm64:3.2.0
    restart: unless-stopped
    volumes:
      - paddlex_models:/root/.paddlex/official_models
      - app_data:/app/data
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    # Ports and environment are intentionally omitted for Dokploy to populate.

volumes:
  paddlex_models:
  app_data:
